### ISSUE TITLE
Not possible to connect to mqtt server with different port

### ISSUE THREAD

**Issue by evilmumi** [git-developer/tvheadend-mqtt#2]
my mqtt host run on non standard port.
it is not possible to edit in docker compose!?

**Comment by git-developer** [comment]
Please check if the environment variables `MQTT_PUBLISH_OPTIONS` / `MQTT_SUBSCRIBE_OPTIONS` fulfil your needs. Their content is appended to the `mosquitto_pub` / `mosquitto_sub` call.

Example:
```yaml
    environment:
      MQTT_PUBLISH_OPTIONS: "-p 1883"
      MQTT_SUBSCRIBE_OPTIONS: "-p 1883"
```
